### ISSUE TITLE
please consider releasing fips203-ffi to crates.io

### ISSUE THREAD

**Issue by dkg** [integritychain/fips203#9]
Thanks for the work on this crate, and the review and merging of the proposed C FFI.

I would find it really useful if the `fips203-ffi` crate were released on crates.io.

If you're up for publishing it there, that would be great!

**Comment by integritychain** [comment]
I like the idea. I am approaching a stopping point on a FIPS 204 update (wrt constant-time) and will then dig into this.

**Comment by dkg** [comment]
great, thank you!  If that works, and i'm able to integrate the released `fips203-ffi` crate into my own workflows (and possibly into debian), then i might take a crack at offering a similar set of FFI and python bindings for the fips204 work too.

**Comment by integritychain** [comment]
I got the clippy fixes sorted out, and also found/fixed a few in the ffi code.
We should be good-to-go with https://crates.io/crates/fips203-ffi
Let me know if it works well for you.
Your help is appreciated!

**Comment by dkg** [comment]
The FFI is now [in debian](https://tracker.debian.org/pkg/rust-fips203-ffi), including the python bindings as well.  I probably need to register it on PyPI to reserve the python module name.  I'll try to do that in the coming week.

Debian users can now `apt install python3-fips203` and it uses your work here, @integritychain.  exciting! ☺

**Comment by integritychain** [comment]
This is great news, thank you very much for your help on this.
I've learned some new stuff from you!
